stages:
  - name: compile
    steps:
      - runScriptConfig:
          image: maven:3.6.2-jdk-8
          shellScript: cd monster-service -Dskiptests clean compile;
  - name: test
    steps:
      - runScriptConfig:
          image: maven:3.6.2-jdk-8
          shellScript: cd monster-service clean package;
  - name: docker
    steps:
      - publishImageConfig:
          dockerfilePath: ./monster-dockerfile
          buildContext: .
          tag: fcs-core:${CICD_GIT_COMMIT}
          pushRemote: true
          registry: repodev.cib.ru:8083
        env:
          PLUGIN_DEBUG: "true"
          PLUGIN_INSECURE: "true"
        when:
          branch:
            include:
              - test
      - publishImageConfig:
          dockerfilePath: ./fcs-processor-dockerfile
          buildContext: .
          tag: fcs-processor:${CICD_GIT_COMMIT}
          pushRemote: true
          registry: repodev.cib.ru:8083
        env:
          PLUGIN_DEBUG: "true"
          PLUGIN_INSECURE: "true"
        when:
          branch:
            include:
              - test
  - name: deploy to TEST
    steps:
      - applyYamlConfig:
          path: ./fcs-processor-deployment.yaml
        when:
          branch:
            include:
              - test
      - applyYamlConfig:
          path: ./fcs-core-deployment.yaml
        when:
          branch:
            include:
              - test
timeout: 60
notification:
  recipients:
    - recipient: s.zadorozhniy@centrinvest.ru
      notifier: c-kshgl:n-g7hch
    - recipient: m.sokolov@centrinvest.ru
      notifier: c-kshgl:n-g7hch
  condition:
    - Success
    - Failed