stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3.6.2-jdk-8
      shellScript: cd monster;mvn -Dskiptests clean compile;
- name: test
  steps:
  - runScriptConfig:
      image: maven:3.6.2-jdk-8
      shellScript: cd monster;mvn clean package;
  - runScriptConfig:
      image: alpine
      shellScript: pwd
  - runScriptConfig:
      image: alpine
      shellScript: ls -la ./monster
- name: docker-image
  steps:
  - publishImageConfig:
      dockerfilePath: ./monster-dockerfile
      buildContext: .
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
timeout: 60
notification: {}
