stages:
  - name: compile
    steps:
      - runScriptConfig:
          image: maven:3.6.2-jdk-8
          shellScript: cd monster -Dskiptests clean compile;
  - name: test
    steps:
      - runScriptConfig:
          image: maven:3.6.2-jdk-8
          shellScript: cd monster clean package;
  - name: docker
    steps:
      - publishImageConfig:
          dockerfilePath: ./monster-dockerfile
          buildContext: .
#          registry: repodev.cib.ru:8083
        env:
          PLUGIN_DEBUG: "true"
          PLUGIN_INSECURE: "true"
timeout: 60
notification:
  recipients:
    - recipient: s.zadorozhniy@centrinvest.ru
      notifier: c-kshgl:n-g7hch
    - recipient: m.sokolov@centrinvest.ru
      notifier: c-kshgl:n-g7hch
  condition:
    - Success
    - Failed