---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: dev
  name: monster
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: monster
        tier: backend
        track: test
    spec:
      containers:
        - name: monster
          image: sabbath666/monster:${CICD_GIT_COMMIT}
          imagePullPolicy: Always
          ports:
            - containerPort:  8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: monster
  namespace: dev
spec:
  selector:
    app: monster
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
