---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: quote
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: quote
        tier: backend
        track: test
    spec:
      containers:
        - name: quote
          image: sabbath666/quote:${CICD_GIT_COMMIT}
          imagePullPolicy: Always
          ports:
            - containerPort:  8080
#        livenessProbe:
#          httpGet:
#            path: /actuator/health
#            port: 8881
#          initialDelaySeconds: 30
#          timeoutSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: quote
  namespace: default
spec:
  selector:
    app: quote
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
