---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  namespace: default
  name: say
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 10%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: say
        tier: backend
        track: test
    spec:
      containers:
        - name: say
          image: sabbath666/say:${CICD_GIT_COMMIT}
          imagePullPolicy: Always
          ports:
            - containerPort:  8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: say
  namespace: default
spec:
  type: NodePort
  selector:
    app: say
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30003
