---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: monnitoring
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:6.3.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-conf
              mountPath: /etc/grafana
            - name: grafana-data
              mountPath: /var/lib/grafana

      volumes:
        - name: grafana-conf
          hostPath:
            path: ~/rancher/monitoring/grafana/conf
        - name: grafana-data
          hostPath:
            path: ~/rancher/monitoring/grafana/data
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 9090
      protocol: TCP
      nodePort: 30090