---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: monnitoring
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.12.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-conf
              mountPath: /etc/prometheus
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: dev
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      protocol: TCP
      nodePort: 30090